<?php

use App\Http\Controllers\Admin\CampaignsController;
use App\Http\Controllers\Admin\CheckinController;
use App\Http\Controllers\Admin\ShippingController;
use App\Http\Controllers\Admin\CustomersController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\OrdersController;
use App\Http\Controllers\Admin\PointsController;
use App\Http\Controllers\Admin\RewardsController;
use App\Http\Controllers\Admin\RolesController;
use App\Http\Controllers\Admin\SettingsController;
use App\Http\Controllers\Admin\StoresController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\PromotionsController;
use App\Http\Controllers\Admin\VariantsController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth', 'admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/badges', [DashboardController::class, 'badges'])->name('badges');
    Route::get('/customers', [CustomersController::class, 'index'])->name('customers.index');
    Route::put('/customers/{customer}', [CustomersController::class, 'update'])->name('customers.update');
    Route::post('/customers/{customer}/toggle', [CustomersController::class, 'toggle'])->name('customers.toggle');
    Route::get('/orders', [OrdersController::class, 'index'])->name('orders.index');
    Route::get('/orders/refresh', [OrdersController::class, 'refresh'])->name('orders.refresh');
    Route::post('/orders/{order}/advance', [OrdersController::class, 'advance'])->name('orders.advance');
    Route::post('/orders/{order}/cancel', [OrdersController::class, 'cancel'])->name('orders.cancel');
    Route::get('/points', [PointsController::class, 'index'])->name('points.index');
    Route::post('/points/adjust', [PointsController::class, 'adjust'])->name('points.adjust');
    Route::get('/rewards', [RewardsController::class, 'index'])->name('rewards.index');
    Route::post('/rewards', [RewardsController::class, 'store'])->name('rewards.store');
    Route::put('/rewards/{reward}', [RewardsController::class, 'update'])->name('rewards.update');
    Route::post('/rewards/{reward}/toggle', [RewardsController::class, 'toggle'])->name('rewards.toggle');
    Route::post('/rewards/{reward}/duplicate', [RewardsController::class, 'duplicate'])->name('rewards.duplicate');
    Route::delete('/rewards/{reward}', [RewardsController::class, 'destroy'])->name('rewards.destroy');
    Route::get('/campaigns', [CampaignsController::class, 'index'])->name('campaigns.index');
    Route::post('/campaigns', [CampaignsController::class, 'store'])->name('campaigns.store');
    Route::put('/campaigns/{campaign}', [CampaignsController::class, 'update'])->name('campaigns.update');
    Route::post('/campaigns/{campaign}/toggle', [CampaignsController::class, 'toggle'])->name('campaigns.toggle');
    Route::post('/campaigns/{campaign}/push', [CampaignsController::class, 'push'])->name('campaigns.push');
    Route::get('/roles', [RolesController::class, 'index'])->name('roles.index');
    Route::post('/roles', [RolesController::class, 'update'])->name('roles.update');
    Route::post('/roles/assign', [RolesController::class, 'assign'])->name('roles.assign');
    Route::delete('/roles/staff/{staff}', [RolesController::class, 'removeStaff'])->name('roles.staff.remove');
    Route::get('/settings', [SettingsController::class, 'index'])->name('settings.index');
    Route::post('/settings', [SettingsController::class, 'update'])->name('settings.update');
    Route::post('/settings/logo', [SettingsController::class, 'uploadLogo'])->name('settings.logo.upload');
    Route::delete('/settings/logo', [SettingsController::class, 'deleteLogo'])->name('settings.logo.delete');
    Route::post('/settings/favicon', [SettingsController::class, 'uploadFavicon'])->name('settings.favicon.upload');
    Route::delete('/settings/favicon', [SettingsController::class, 'deleteFavicon'])->name('settings.favicon.delete');
    Route::get('/stores', [StoresController::class, 'index'])->name('stores.index');
    Route::post('/stores', [StoresController::class, 'store'])->name('stores.store');
    Route::put('/stores/{store}', [StoresController::class, 'update'])->name('stores.update');
    Route::post('/stores/{store}/toggle', [StoresController::class, 'toggle'])->name('stores.toggle');
    Route::delete('/stores/{store}', [StoresController::class, 'destroy'])->name('stores.destroy');
    Route::post('/stores/{store}/photos', [StoresController::class, 'uploadPhoto'])->name('stores.photos.upload');
    Route::delete('/stores/{store}/photos', [StoresController::class, 'deletePhoto'])->name('stores.photos.delete');
    Route::get('/promotions', [PromotionsController::class, 'index'])->name('promotions.index');
    Route::post('/promotions', [PromotionsController::class, 'store'])->name('promotions.store');
    Route::post('/promotions/{promotion}', [PromotionsController::class, 'update'])->name('promotions.update');
    Route::delete('/promotions/{promotion}', [PromotionsController::class, 'destroy'])->name('promotions.destroy');
    Route::post('/promotions/{promotion}/toggle', [PromotionsController::class, 'toggle'])->name('promotions.toggle');
    Route::get('/shipping', [ShippingController::class, 'index'])->name('shipping.index');
    Route::post('/shipping', [ShippingController::class, 'store'])->name('shipping.store');
    Route::put('/shipping/{shipping}', [ShippingController::class, 'update'])->name('shipping.update');
    Route::delete('/shipping/{shipping}', [ShippingController::class, 'destroy'])->name('shipping.destroy');
    Route::post('/shipping/reorder', [ShippingController::class, 'reorder'])->name('shipping.reorder');
    Route::post('/shipping/promos', [ShippingController::class, 'storePromo'])->name('shipping.promos.store');
    Route::put('/shipping/promos/{promo}', [ShippingController::class, 'updatePromo'])->name('shipping.promos.update');
    Route::delete('/shipping/promos/{promo}', [ShippingController::class, 'destroyPromo'])->name('shipping.promos.destroy');
    Route::post('/shipping/promos/{promo}/toggle', [ShippingController::class, 'togglePromo'])->name('shipping.promos.toggle');
    Route::get('/variants', [VariantsController::class, 'index'])->name('variants.index');
    Route::post('/variants/groups', [VariantsController::class, 'storeGroup'])->name('variants.groups.store');
    Route::post('/variants/groups/reorder', [VariantsController::class, 'reorderGroups'])->name('variants.groups.reorder');
    Route::post('/variants/groups/{group}', [VariantsController::class, 'updateGroup'])->name('variants.groups.update');
    Route::delete('/variants/groups/{group}', [VariantsController::class, 'destroyGroup'])->name('variants.groups.destroy');
    Route::post('/variants/options', [VariantsController::class, 'storeOption'])->name('variants.options.store');
    Route::put('/variants/options', [VariantsController::class, 'updateOption'])->name('variants.options.update');
    Route::delete('/variants/options', [VariantsController::class, 'destroyOption'])->name('variants.options.destroy');
    Route::post('/variants/options/toggle', [VariantsController::class, 'toggleOption'])->name('variants.options.toggle');
    Route::post('/variants/options/toggle-all', [VariantsController::class, 'toggleAllOptions'])->name('variants.options.toggle-all');
    Route::post('/variants/groups/{group}/set-default', [VariantsController::class, 'setDefault'])->name('variants.groups.setDefault');
    Route::get('/menu', [MenuController::class, 'index'])->name('menu.index');
    Route::post('/menu/products', [MenuController::class, 'storeProduct'])->name('menu.products.store');
    Route::post('/menu/products/{product}', [MenuController::class, 'updateProduct'])->name('menu.products.update');
    Route::delete('/menu/products/{product}', [MenuController::class, 'destroyProduct'])->name('menu.products.destroy');
    Route::post('/menu/products/{product}/toggle', [MenuController::class, 'toggleProduct'])->name('menu.products.toggle');
    Route::post('/menu/categories', [MenuController::class, 'storeCategory'])->name('menu.categories.store');
    Route::post('/menu/categories/{category}', [MenuController::class, 'updateCategory'])->name('menu.categories.update');
    Route::delete('/menu/categories/{category}', [MenuController::class, 'destroyCategory'])->name('menu.categories.destroy');
    Route::get('/checkin', [CheckinController::class, 'index'])->name('checkin.index');
    Route::post('/checkin', [CheckinController::class, 'update'])->name('checkin.update');
});
